#!/bin/ruby

line = ?- * `tput cols`.to_i

Dir.glob "*.rb" do |filename|
	puts <<~TEXT
		
		#{line}
		- Now running '#{filename}'
		#{line}
		
	TEXT
	
	system "ruby #{filename}"
end


puts <<~TEXT
	
	#{line}
	End of run.
	#{line}
	
TEXT


