#!/bin/ruby

line = ?- * `tput cols`.to_i

DEBUG = ARGV == ["DEBUG"]
start = Time.now if DEBUG


Dir.glob "*.rb" do |filename|
	
	puts <<~TEXT
		
		#{line}
		- Now running '#{filename}'
		#{line}
		
	TEXT
	
	this_start = Time.now if DEBUG
	
	system "ruby #{filename}"
	
	puts <<~TEXT % (Time.now - this_start) if DEBUG
		
		#{line}
		This run took %.4f seconds
	TEXT
	
end


puts <<~TEXT % (Time.now - start) if DEBUG
	#{line}
	End of run.
	Total time: %.4f seconds
	#{line}
TEXT


